/* Automatically generated by create_config - do not modify */
#define TARGET_SHORT_ALIGNMENT 2
#define TARGET_INT_ALIGNMENT 4
#define TARGET_LONG_ALIGNMENT 4
#define TARGET_LLONG_ALIGNMENT 8
#define TARGET_ARCH "cris"
#define TARGET_CRIS 1
#define TARGET_TYPE TARGET_TYPE_CRIS
#define CONFIG_NO_XEN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-cris"
#define CONFIG_LINUX_USER 1
#define CONFIG_USE_NPTL 1
#define CONFIG_USE_GUEST_BASE 1
#define CONFIG_I386_DIS 1
#define CONFIG_CRIS_DIS 1
