/* Automatically generated by create_config - do not modify */
#define TARGET_SHORT_ALIGNMENT 2
#define TARGET_INT_ALIGNMENT 4
#define TARGET_LONG_ALIGNMENT 4
#define TARGET_LLONG_ALIGNMENT 8
#define TARGET_ARCH "unicore32"
#define TARGET_UNICORE32 1
#define TARGET_TYPE TARGET_TYPE_UNICORE32
#define CONFIG_NO_XEN 1
#define TARGET_PHYS_ADDR_BITS 32
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
